spring.application.name=sb-ecom

spring.h2.console.enabled = true
spring.datasource.url= jdbc:h2:mem:mann

spring.jpa.show-sql= true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

project.image = images/

spring.app.jwtSecret =mySecretKey1239gffrewsdfsdfevhrfhiweuhfwefyqdgnsachew235djvbdshfguweifgyw3qevfd12738
spring.app.jwtExpirationMs= 86400000

logging.level.org.springframework =DEBUG
logging.level.org.hibernate.SQL = DEBUG
logging.level.org.springframework.security = DEBUG
logging.level.com.ecommerce.project = DEBUG